[general]
import = ["~/.config/alacritty/themes/noctalia.toml"]

[window]
opacity = 0.9
padding = {x = 10, y = 10}
decorations = 'None'

[font]
normal = { family = "JetBrains Mono Nerd Font Propo", style = "Regular" }
size = 15

[cursor]
blink_interval = 500
style = {blinking = "always"}

