[window]
opacity = 0.8
blur = true
padding = {x = 16, y = 10}
decorations = 'None'

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 16

[general]
import = [ "~/.config/alacritty/themes/noctalia.toml",
]
