[colors.primary]
background = '#11131a'
foreground = '#e2e2eb'

[colors.cursor]
text = '#11131a'
cursor = '#e2e2eb'

[colors.vi_mode_cursor]
text = '#11131a'
cursor = '#b3c5ff'

[colors.search.matches]
foreground = '#434653'
background = '#f6adff'

[colors.search.focused_match]
foreground = '#434653'
background = '#b3c5ff'

[colors.footer_bar]
foreground = '#434653'
background = '#e2e2eb'

[colors.hints.start]
foreground = '#434653'
background = '#b8c5f4'

[colors.hints.end]
foreground = '#434653'
background = '#b8c5f4'

[colors.selection]
text = '#c4c6d5'
background = '#434653'


[colors.normal]
black   = '#434653'
red     = '#ffb4ab'
green   = '#b3c5ff'
yellow  = '#b8c5f4'
blue    = '#f6adff'
magenta = '#b3c5ff'
cyan    = '#b8c5f4'
white   = '#e2e2eb'


[colors.bright]
black   = '#8d909e'
red     = '#ffb4ab'
green   = '#b3c5ff'
yellow  = '#b8c5f4'
blue    = '#f6adff'
magenta = '#b3c5ff'
cyan    = '#b8c5f4'
white   = '#e2e2eb'


[colors.dim]
black   = '#434653'
red     = '#ffb4ab'
green   = '#b3c5ff'
yellow  = '#b8c5f4'
blue    = '#f6adff'
magenta = '#b3c5ff'
cyan    = '#b8c5f4'
white   = '#e2e2eb'
