[colors.primary]
background = '#121316'
foreground = '#e3e2e6'

[colors.cursor]
text = '#121316'
cursor = '#e3e2e6'

[colors.vi_mode_cursor]
text = '#121316'
cursor = '#b1c6f6'

[colors.search.matches]
foreground = '#44474e'
background = '#e9b7e3'

[colors.search.focused_match]
foreground = '#44474e'
background = '#b1c6f6'

[colors.footer_bar]
foreground = '#44474e'
background = '#e3e2e6'

[colors.hints.start]
foreground = '#44474e'
background = '#bfc6db'

[colors.hints.end]
foreground = '#44474e'
background = '#bfc6db'

[colors.selection]
text = '#c4c6cf'
background = '#44474e'


[colors.normal]
black   = '#44474e'
red     = '#ffb4ab'
green   = '#b1c6f6'
yellow  = '#bfc6db'
blue    = '#e9b7e3'
magenta = '#b1c6f6'
cyan    = '#bfc6db'
white   = '#e3e2e6'


[colors.bright]
black   = '#8e9099'
red     = '#ffb4ab'
green   = '#b1c6f6'
yellow  = '#bfc6db'
blue    = '#e9b7e3'
magenta = '#b1c6f6'
cyan    = '#bfc6db'
white   = '#e3e2e6'


[colors.dim]
black   = '#44474e'
red     = '#ffb4ab'
green   = '#b1c6f6'
yellow  = '#bfc6db'
blue    = '#e9b7e3'
magenta = '#b1c6f6'
cyan    = '#bfc6db'
white   = '#e3e2e6'
